### PR TITLE
API Supported module status improvements:

### PR DESCRIPTION
**Pull request by tractorcow**
- PSR-2
- Transifex configuration
- Changelog template
- Scrutinizer configuration
- Gitattributes
- Gitignore
- Editorconfig
- Fix incorrect composer license reference

### CODE REVIEW

**Comment by tractorcow** [comment]
Sorry @helpfulrobot I beat you to it. :D

**Comment by tractorcow** [comment]
The tests don't work so no point adding it until we fix them. :D

**Comment by dhensby** [comment]
unless you want a constant reminder....

**Comment by tractorcow** [comment]
Ok, I'll add them... passing or not. ;P

**Comment by tractorcow** [comment]
Ok, .travis.yml added. :D

**Comment by madmatt** [comment]
Wow, @helpfulrobot is creepily human haha.

**Comment by dhensby** [comment]
I don't have merge perms

**Comment by stevie-mayhew** [comment]
Travis is failing but I'll allow it :wink:

**Comment by tractorcow** [comment]
Thanks; Tests need to be fixed in the upcoming days.

**Pull request merged**
