### PR TITLE
API init saml2 library with stand-alone bootstrap.php

### PR DESCRIPTION
**Pull request by tractorcow**
Replaces the custom fixes in the below commits:

- https://github.com/madmatt/simplesamlphp/commit/43a910d49106ea60dee9f771a6347649917098cf
- https://github.com/madmatt/simplesamlphp/commit/e0d5ca8da8a10a611e45651b122486d5eb7da1eb

I've also checked that https://github.com/madmatt/simplesamlphp/commit/e7d0e1975cf87261256ae74ea852552812b5aecb is fixed in upstream, so maybe we should rebase it?

### CODE REVIEW

**Comment by tractorcow** [comment]
If this is merged then my next action will be to remove the old hacks.

I'll do this by force pushing:
https://github.com/madmatt/simplesamlphp/commits/ss-master-2

Up to
https://github.com/madmatt/simplesamlphp/commits/ss-master

**Comment by madmatt** [comment]
As well as overriding `HTTPS`, you also need to set `$_SERVER['SERVER_PORT'] = '443';` (note that it must be a string constant, not an int)

**Comment by tractorcow** [comment]
I'll implement a fix that also respects `$_SERVER['HTTP_X_FORWARDED_PORT']`. :)

**Comment by tractorcow** [comment]
How does it look now @madmatt ?

**Comment by madmatt** [comment]
Awesome, thanks @tractorcow!

**Comment by tractorcow** [comment]
OK, hack removed from the forked simplesamlphp library too. :)

**Pull request merged**
